name: Flutter CI

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches:
      - master

# on: push    # Default will running for every branch.

jobs:
  test_build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - run: sudo apt-get update
    - run: sudo apt-get install apt-transport-https
    - run: sudo sh -c 'wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
    - run: sudo sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
    - run: sudo apt-get update
    - run: sudo apt-get install dart
    - run: export PATH="$PATH:/usr/lib/dart/bin"
    - run: echo 'export PATH="$PATH:/usr/lib/dart/bin"' >> ~/.profile
    - run: sudo snap install flutter --classic
    - run: flutter sdk-path
    - run: pwd
    - run: ls
    - run: ls -a
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk

