name: Flutter CI

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches:
      - master

# on: push    # Default will running for every branch.

jobs:
  test_build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get update    
    - run: sudo snap install flutter --classic
    - run: flutter sdk-path
    - run: pwd
    - run: ls
    - run: ls -a
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk

