name: Flutter CI

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches:
      - master

# on: push    # Default will running for every branch.

jobs:
  test_build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: '1.22.4'
      - run: dart --version
      - run: flutter --version
      - run: flutter upgrade
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --release
